name: notas
description: "Aplicacion de notas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.9.1
  #imagenes
  image_picker: ^1.0.7
  
  # Iconos y estilos visuales
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  # <--- Esta es la modificación para estilos únicos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Configuración para el logo de la Unison 
  assets:
    - assets/